log_level: DEBUG
database:
  host: localhost:3306
  user: johannes
  password: U9rAruUB.xyHpKJcLXdW
  database: johannes_pv
cache:
  expiration: 12h
  purge: 12h
client_session:
  jwt_signature: EaX/K6%säQcüFHu+s-{<e(*L4+N8@Ü1g=2NPPüv|"{K.§kv70ZRbzq%KBdN8aW;ü05S(HmH§)rÖc&-(Rö3P6{>'Y<8wEüq2WVDv3
  expire: 168h
server:
  port: 61016
