log_level: DEBUG
database:
  host: localhost:3306
  user: johannes
  password: U9rAruUB.xyHpKJcLXdW
  database: johannes_pv
cache:
  expiration: 12h
  purge: 12h
client_session:
  jwt_signature: =$,k)tÄ_XNe{jA3NeÖzÜ(°°']0BXM}&fnq-?ü:Rb9HvOQ$Gü$O65cF}ßZ5T}Wosßy(wß1O*|pL0(:$ä/C1R*fzs4jw)"Gbh<,öwK
  expire: 168h
server:
  port: 61016
