log_level: DEBUG
database:
  host: localhost:3306
  user: johannes
  password: U9rAruUB.xyHpKJcLXdW
  database: johannes_pv
cache:
  expiration: 12h
  purge: 12h
client_session:
  jwt_signature: $oD0ö('i14|8]!D*n<ÖvA7:8Q#JXk$EH|!"DmwEz)[1YUwL§6A9QkeC)+:nz9RCygzVC#tKS8<d[_,k°L|ße(ä@BOHA%K2RT°X7N
  expire: 168h
server:
  port: 61016
