log_level: INFO
database:
  host: localhost:3306
  user: user
  password: password
  database: database_name
cache:
  expiration: 12h
  purge: 12h
client_session:
  jwt_signature: auto_generated_from_setup
  expire: 168h
server:
  port: 61016
reservation:
  expiration: 168h
mail:
  server: smtp.example.org
  port: 587
  user: user@example.org
  password: PASSWORD
  template:
    subject: {{.ElementType}} {{.Element}}
    body_plain: plain-text-body
    body: html-body